apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ij16lfs5s-nodejs-gitops
  description: This is GitOps manifest for ij16lfs5s-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ij16lfs5s-nodejs
    backstage.io/kubernetes-id: ij16lfs5s-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: ij16lfs5s-nodejs-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ij16lfs5s-nodejs
