apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ij16lfs5s-nodejs
  janus-idp.io/tekton: ij16lfs5s-nodejs
  backstage.io/kubernetes-id: ij16lfs5s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ij16lfs5s-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
