apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ij16lfs5s-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ij16lfs5s-nodejs 
  name: ij16lfs5s-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ij16lfs5s-nodejs 
